---
- hosts: all
  become: true
  tasks:

    - name: Create a network with custom IPAM config
      docker_network:
        name: network_three
        ipam_config:
        - subnet: 172.168.10.0/30  
          gateway: 172.168.10.2
          iprange: 172.168.10.0/32
          aux_addresses:
            host1: 172.168.10.3
            host2: 172.168.10.4
    
    - name: Pull a Docker Image
      docker_image: 
        name: httpd
        tag: latest
        source: pull
      register: z
    - name: Checking Pull Status
      debug: 
        var: z

    - name: Creating a Persistent Volume Dir
      file:
        path: "/home/ubuntu/DockerVolume"
        state: directory

    - name: Copying the HTML code in the Directory
      copy: 
        src: "templates/index.html"
        dest: "/home/ubuntu/DockerVolume"

    - name: Launching an HTTPD Container
      when: z.failed == false
      docker_container:
        name: apache-server
        image: httpd
        state: started
        exposed_ports:
          - "80"
        ports:
          - "8888:80"
        volumes: 
          - /home/ubuntu/DockerVolume:/usr/local/apache2/htdocs